services:
  postgres_configuration:
    image: postgres:latest
    container_name: configuration_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: config_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  postgres_generation:
    image: postgres:latest
    container_name: generation_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: generation_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network: